version: '3.8'

services:
  customers-api:
    container_name: api
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9299
    env_file: .env
    networks:
      - default
    depends_on: 
      - redis

  redis:
    container_name: redis
    image: redis
    networks:
      - default

networks:
  default: